function VarName3 = import_float(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   VarName3 = IMPORTFILE(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as
%   column vectors.
%
%   VarName3 = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   VarName3 = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the
%   specified worksheet for the specified row interval(s). Specify STARTROW
%   and ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   VarName3 = importfile('test.xlsx','Tabelle1',6,6);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/08/23 11:59:12

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 6;
    endRow = 6;
end

%% Import the data
data = xlsread(workbookFile, sheetName, sprintf('C%d:C%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    tmpDataBlock = xlsread(workbookFile, sheetName, sprintf('C%d:C%d',startRow(block),endRow(block)));
    data = [data;tmpDataBlock]; %#ok<AGROW>
end

%% Allocate imported array to column variable names
VarName3 = data(:,1);

