function MeasuredRnConcentrations = import_river_depth(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   MeasuredRnConcentrations = IMPORTFILE(FILE) reads data from the first
%   worksheet in the Microsoft Excel spreadsheet file named FILE and
%   returns the data as column vectors.
%
%   MeasuredRnConcentrations = IMPORTFILE(FILE,SHEET) reads from the
%   specified worksheet.
%
%   MeasuredRnConcentrations = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads
%   from the specified worksheet for the specified row interval(s). Specify
%   STARTROW and ENDROW as a pair of scalars or vectors of matching size
%   for dis-contiguous row intervals. To read to the end of the file
%   specify an ENDROW of inf.
%
%	Blank cells are replaced with: NaN
%
% Example:
%   MeasuredRnConcentrations = importfile('test.xlsx','Tabelle1',4,27);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/08/23 14:17:52

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 4;
    endRow = 27;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('K%d:K%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('K%d:K%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace blank cells with NaN
R = cellfun(@(x) isempty(x) || (ischar(x) && all(x==' ')),raw);
raw(R) = {NaN}; % Replace blank cells

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
MeasuredRnConcentrations = data(:,1);

